version: '2'
services:
  wecross-demo:
    build: .
    container_name: wecross-demo
    hostname: wecross
    ports:
      - 8260:8250
    tty: true
    stdin_open: true
    restart: "no"
    image: wecross-demo:latest
    volumes: 
      - ./certs:/fabric_certs/
