[connection]
    server =  '127.0.0.1:8250'
    sslKey = 'classpath:ssl.key'
    sslCert = 'classpath:ssl.crt'
    caCert = 'classpath:ca.crt'
    sslSwitch = 2
    urlPrefix = 'wecross'
[login]
    username = 'org1-admin'
    password = '123456'